language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
jobs:
  include:
    - stage: test
      node_js: "node"
      script:
        - npm test
    - stage: coverage
      node_js: "node"
      script:
        - npm run test:coverage
    - stage: lint
      node_js: "node"
      script:
        - npm run lint:prettier
        - npm run lint:js
